FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y wget gnupg curl unzip fonts-liberation libnss3 libatk-bridge2.0-0 libxss1 libgtk-3-0 libasound2 libdrm2 libgbm1 libxshmfence1 libxrandr2 libxcomposite1 libxdamage1 libxfixes3 libxext6 libx11-6 libgl1-mesa-glx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy code
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN playwright install --with-deps

# Start server
CMD ["python", "main.py"]
